version: 2
# inspired by https://github.com/CircleCI-Public/circleci-demo-javascript-express
jobs:
  build:
    docker:
      - image: circleci/node:6.10
    steps:
      - checkout
      - restore_cache:
          key: server-cache-{{ checksum "package.json" }}
      - restore_cache:
          key: client-cache-{{ checksum "client/package.json" }}
      - run:
          name: install-npm-wee
          command: npm install
      - run:
          name: install-npm-client
          command: cd cient && npm install    
      - save_cache:
          key: server-cache-{{ checksum "package.json" }}
          paths:
            - ./node_modules
      - save_cache:
          key: client-cache-{{ checksum "client/package.jsonn" }}
          paths:
            - ./client/node_modules      
      - run:
          name: parser - test & coveralls
          command: npm run coveralls
      - store_artifacts:
          path: test-results.xml
          prefix: tests